// <auto-generated />
using System;
using GEC.InspectionService.Data.Adapter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GEC.InspectionService.Data.Migrations
{
    [DbContext(typeof(InspectionServiceDBContext))]
    partial class InspectionServiceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GEC.InspectionService.Data.States.GasInspectionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CO")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CO2")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HC")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Lambda")
                        .HasColumnType("numeric");

                    b.Property<int?>("NO")
                        .HasColumnType("integer");

                    b.Property<decimal?>("O2")
                        .HasColumnType("numeric");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GasInspections", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
